<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6"/>
        <PackageReference Include="Castle.Core" Version="5.2.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.*"/>
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.6"/>

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.6">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2"/>
        <PackageReference Include="MessageBox.Avalonia" Version="3.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DuplicateFileFinderLib\DuplicateFileFinderLib.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**\*.*"/>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>DuplicateFileFinder.GuiTests</_Parameter1>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
