<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2"/>
        <PackageReference Include="xunit" Version="2.*"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.*"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*"/>
        <!-- <PackageReference Include="coverlet.collector" Version="8.*" /> -->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DuplicateFileFinderLib\DuplicateFileFinderLib.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Grouping\" />
    </ItemGroup>

    <PropertyGroup>
        <DefineConstants>JETBRAINS_ANNOTATIONS</DefineConstants>
    </PropertyGroup>

</Project>
